---
kind: pipeline
name: release
workspace:
  path: veselahouba.bareos
when:
  event:
    - tag
steps:
  - name: publish
    image: veselahouba/molecule
    environment:
      GALAXY_API_KEY:
        from_secret: GALAXY_API_KEY
    commands:
      - >
        ansible-galaxy role import --api-key $${GALAXY_API_KEY}
        $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}
